### ISSUE TITLE
Only works with LF line endings

### ISSUE THREAD

**Issue by pdudits** [opendevise/downdoc#16]
Downdoc only works on files with lf line endings. None of the blocks seem to be identified and translated when file has CRLF line endings.

For example:

```
= Crlf file

Some preface

== No further block is identified
```

gets converted to

``` 
# Crlf file
Some preface

== No further block is identified
```

**Comment by mojavelinux** [comment]
The current functionality is behaving as designed. I have no plans to add support for Windows newlines. If you have a document with Windows newlines, you'll need to convert that document before passing it to downdoc. You can do that using a tool like dos2unix or similar.
