### ISSUE TITLE
Title outputs are wrong

### ISSUE THREAD

**Issue by edl7878** [opendevise/downdoc#17]
* Platform: windows

* npm --version: 10.8.1

* npm list -g --depth=0: downdoc@1.0.2-stable

* node --version: v20.16.0 with downdoc installed globally

* command: npx downdoc "test.adoc"

### Adoc content

```
# Example

## head2

### head3

#### head4

##### head5

###### head6
```

### md output

```
# Example

## head2

<mark>#</mark> head3

<mark>#</mark># head4

<mark>#</mark>## head5

<mark>#</mark><mark>#</mark> head6
```

**Comment by mojavelinux** [comment]
downdoc does not support Markdown-style headings in AsciiDoc. This is mentioned in the README (look for atx-style only in https://github.com/opendevise/downdoc/?tab=readme-ov-file#supported-syntax). And there's no plan to add support for them. You'll need to convert them before using downdoc.

**Comment by edl7878** [comment]
Got it, Thanks

**Comment by mojavelinux** [comment]
I've added this requirement to the README.
